### ISSUE TITLE
Exporting objects from multiple entrypoints?

### ISSUE THREAD

**Issue by brandonweiss** [eventualbuddha/rollup-plugin-multi-entry#1]
I have a number of modules which I'd like to merge/assign together into an IIFE. E.g.

```javascript
// a.js

export default {

  foo: function() {},

  bar: function() {}

}
```

```javascript
// b.js

export default {

  baz: function() {},

  qux: function() {}

}
```

But I can't quite figure out how to do that. The closest I can get is:

```javascript
// a.js

export const foo = function() {}

export const bar = function() {}
```

```javascript
// b.js

export const baz = function() {}

export const qux = function() {}
```

Which technically works, but it seems not ideal. This slightly changes the behavior of the module, right? Technically I'm changing the module in order to now get the output I want, right? Is there another way to do what I'm trying to do? Or is this something that would make sense to add to multi-entry?

**Comment by eventualbuddha** [comment]
The second way is correct, where each function is its own export. Exporting a default object with named function properties is an anti-pattern, as far as I'm concerned. The only thing I could see a case for changing is to make multi-entry throw when you have two modules exporting the same name (`default`, in this case).

**Comment by brandonweiss** [comment]
Ah, can you expound a little more? Why is it an anti-pattern? The vast majority of libraries seems to export a default object? Or are you saying it's just an anti-pattern in this case for the modules within the library itself?

**Comment by eventualbuddha** [comment]
Many libraries do export a default object, but that makes it hard/impossible for tools like rollup to perform tree-shaking. Not to mention the fact that it artificially couples the exported values together.

You can't really avoid this with CommonJS since you either set properties on an `exports` object or replace `module.exports`, but ES modules allow you to keep things separate and import them separately.

I hope that clarifies it a little bit.

**Comment by brandonweiss** [comment]
Interesting, thanks for explaining. I'll give it a shot!
